### ISSUE TITLE
Update error "has additional properties" to have array with additional properties names

### ISSUE THREAD

**Issue by ceoworks** [debitoor/schemagic#8]
Suppose we have a schema with such a properties userSchema = {name, surname}
But in he input we receive object that looks like input = {name, surname, login}
When validate accross userSchema, error must contain 'forbiddenProperties' array besides message and property fields.
Example: { message: 'has additional properties', property: 'data', additonalProperties: [ 'login' ] }

Kind Regards

**Comment by ebdrup** [comment]
I completely agree that this should be improved.
That's really a change needed in (is-my-json-valid)[https://github.com/mafintosh/is-my-json-valid], please create an issue there :-).

**Comment by ceoworks** [comment]
Open duplicate on their repo
https://github.com/mafintosh/is-my-json-valid/issues/102

**Comment by wtfil** [comment]
fixed with https://github.com/debitoor/schemagic/commit/b103f8340a31571e00e2e1f9ee10a7fe0273354a
